version: '3.8'

services:
  proap_api:
    build:
      context: ./proap-api
    container_name: proap_api
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - API_PORT=8080
      - DB_HOST=proap_production_db
      - DB_PORT=5432
      - DB_NAME=proap
      - DB_USERNAME=proap
      - DB_PASSWORD=${DB_PASSWORD}
      - FILE_UPLOAD_DIR=/app/uploads
      - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}
      - MAIL_ENABLED=${MAIL_ENABLED}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - SPRING_PROFILES_ACTIVE=prod
      # - MAIL_FROM=${MAIL_FROM}
      # - MAIL_FROM_NAME=${MAIL_FROM_NAME}
    ports:
      - "8080:8080"
    depends_on:
      - proap_production_db

  proap_production_db:
    image: postgres:latest
    container_name: proap_production_db
    environment:
      - POSTGRES_DB=proap
      - POSTGRES_USER=proap
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - proap_db_data:/var/lib/postgresql/data

volumes:
  proap_db_data: