version: '3.8'

services:
  proap_api:
    image: maven:3-eclipse-temurin-21-alpine
    volumes:
      - ./proap-api:/app
    working_dir: /app
    command: ["sh", "-c", "mvn clean -am install -DskipTests && mvn spring-boot:run"]
    environment:
      - API_PORT=8080
      - DB_HOST=proap_dev_db
      - DB_PORT=5432
      - DB_NAME=proap
      - DB_USERNAME=proap
      - DB_PASSWORD=password
      - FILE_UPLOAD_DIR=/app/uploads
      - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}
      - MAIL_ENABLED=${MAIL_ENABLED}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_FROM_ALIAS=${MAIL_FROM_ALIAS}
    ports:
      - "8080:8080"
    depends_on:
      - proap_dev_db

  proap_dev_db:
    image: postgres:latest
    container_name: proap_dev_db
    environment:
      - POSTGRES_DB=proap
      - POSTGRES_USER=proap
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - proap_dev_db_data:/var/lib/postgresql/data

volumes:
  proap_dev_db_data: