export { default as LoginPage } from './login/LoginPage'
export { default as RegisterPage } from './register/RegisterPage'
export { default as NotFoundPage } from './not-found/NotFoundPage'
export { default as HomePage } from './home/HomePage'
export { default as SolicitationPage } from './solicitation/SolicitationPage'
export { default as RecoverPasswordPage } from './recover-password/RecoverPassword'
